
swagger: '2.0'
info:
    title: CSPWeb Reasoner
    description: Solver for CSP Problems
    version: "1.0.0"
host: CSPWebReasoner.service.governify.io
schemes:
    - https
basePath: /api/v1
produces:
    - application/json
paths:
    /problems:
        post:
            description: Submit a new problem
            operationId: addProblem
            produces:
                - application/json
            parameters:
                - 	name: problem
                    in: body
                    description: problem
                    required: true
                    schema:
                        $ref: '#/definitions/problem'
            responses:
               '200':
                    description: Problem registered
                    schema:
                        $ref: '#/definitions/problem'
                default:
                    description: Error
                    schema:
                       $ref: '#/definitions/errorModel'
                       
    /problems/{id}:
        get:
            description: Get a problem optimization result
            operationId: getProblemResult
            produces:
                - application/json
            parameters:
                - 	name: id
                    in: path
                    description: ID of problem
                    required: true
                    type: integer
                    format: int64

            responses:
                '202':
                    description: Problem is being processed
                '200':
                    description: Problem result
                    schema:
                        $ref: '#/definitions/problem'
                default:
                    description: Error
                    schema:
                        $ref: '#/definitions/errorModel'
definitions:
    problem:
        type: object
        required:
            - definition
            - owner
        properties:
            id:
                type: integer
                format: int64
            definition:
                type: string
            solution:
                type: string
            owner:
                type: string
    errorModel:
        type: object
        required:
            - code
            - message
        properties:
            code:
                type: integer
                format: int32
            message:
                type: string